on: [push]

jobs:
  spring_docker_job:
    runs-on: ubuntu-latest
    name: A job to spring boot sample
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: insproworks/spring-action@master
      - name: docker build
        #uses: ./ # Uses an action in the root directory
        uses: insproworks/spring-action@master # Uses an action in the root directory
        id: spring
        with:
          who-to-greet: 'docker build'
      # Use the output from the `hello` step
      - name: Get the output time for docker build
        run: echo "The time was ${{ steps.spring.outputs.time }}"
